---
# MD024/no-duplicate-heading/no-duplicate-header
# Multiple headings with the same content
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024
MD024:
  # Only check sibling headings
  # For CHANGLEOG
  allow_different_nesting: true
