---
# Can't use YAML anchors in the pre-commit configuration.
default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
      - id: check-pre-commit-ci-config

ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "build(git-hook): update pre-commit hooks"
  autofix_commit_msg: |
    fix(git-hook): auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
