---
# Can't use YAML anchors in the pre-commit configuration.
default_stages:
  - commit

repos:
  # Shell
  # Format
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.5.1-1
    hooks:
      - id: shfmt
  # Lint
  # https://github.com/koalaman/shellcheck#pre-commit
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
        args: [--severity=style]
  - repo: https://github.com/hituzi-no-sippo/pre-commit-hook-with-shellharden
    rev: ed57b90bb6a7c64bf5655c50bac082e67b157c00
    hooks:
      - id: shellharden

  # JSON & YAML
  # Formatter
  - repo: https://github.com/adamchainz/pre-commit-dprint
    rev: v0.32.1
    hooks:
      - id: dprint
        types_or:
          - json
          - yaml
          - markdown

  # JSON
  # Lint
  - repo: https://github.com/TomWright/dasel
    rev: v1.27.1
    hooks:
      - id: dasel-validate
        types:
          - json

  # YAML
  # Lint
  # https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [--strict]

  # TOML
  # Format
  - repo: https://github.com/hituzi-no-sippo/pre-commit-hooks-toml-with-taplo
    rev: v1.0.0
    hooks:
      - id: taplo-format
      - id: taplo-lint

  # INI
  # Format
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        files: ^.*\.ini$

  # GitHub Actions
  # Lint
  # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#pre-commit
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.21
    hooks:
      - id: actionlint

  # Spell
  - repo: https://github.com/crate-ci/typos
    rev: v1.10.3
    hooks:
      - id: typos-src

  # Markdown
  # Lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-fix

  # Commit message
  # Lint
  # Conventional Commits
  - repo: https://github.com/hituzi-no-sippo/pre-commit-hooks-with-cocogitto
    rev: 93f9ff191297b6b2973bba4b203ac112bac5186d
    hooks:
      - id: lint-commit-msg-with-cocogitto
  # Style
  - repo: local
    hooks:
      - id: format-commit-msg
        name: format commit message
        language: script
        entry: scripts/git/format-commit-msg.sh
        stages:
          - commit-msg
      # Natural Language
      - id: lint-natural-language-text-of-commit-msg
        name: lint natural language of commit message with vale
        language: script
        entry: scripts/git/lint-natural-language-text-of-commit-msg.sh
        stages:
          - commit-msg

  # Natural Language
  - repo: https://github.com/hituzi-no-sippo/pre-commit-hooks-with-vale
    rev: v1.0.0
    hooks:
      - id: vale

  # CHANGELOG
  - repo: local
    hooks:
      - id: lint-generated-CHANGELOG-with-markdown-linter
        name: lint generated CHANGELOG with markdownlint-cli of markdown linter
        language: script
        entry: scripts/release/lint-generated-CHANGELOG.sh
        files: cliff.toml

  # Link
  - repo: https://github.com/hituzi-no-sippo/pre-commit-hooks-with-lychee
    rev: affc8b2a9a89ff975f251e317e076b6aabd2a21b
    hooks:
      - id: lychee
        args:
          - --cache
          - --max-cache-age=1d

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Style
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # Git
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      # File
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-added-large-files
      # Shebang
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # Symlink
      - id: check-symlinks
      - id: destroyed-symlinks
      # Security
      - id: detect-private-key

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
      - id: check-pre-commit-ci-config

ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "build(git-hook): update pre-commit hooks"
  autofix_commit_msg: |
    fix(git-hook): auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci

  skip:
    - shellcheck
    - shellharden
    - dprint
    - taplo-format
    - taplo-lint
    - actionlint
    - vale
    - format-commit-msg
    - lint-natural-language-text-of-commit-msg
    - lint-generated-CHANGELOG-with-markdown-linter
    - lychee
