= Release
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.9.0
:revdate: 2022-08-07T14:02:46+09:00
:revremark: add pre-commit hook to lint generated CHANGELOG
:description: Release
:copyright: Copyright (C) 2022 {author}
// Custom Attributes
:creation_date: 2022-07-14T16:37:15+09:00
:github_url: https://github.com
:root_directory: ../../..
:pre_commit_config_file: {root_directory}/.pre-commit-config.yaml
:workflows_directory: {root_directory}/.github/workflows

:git_cliff_url: {github_url}/orhun/git-cliff
Using link:{git_cliff_url}[git-cliff^] to generate CHANGELOG and Release Note.

[horizontal]
`CHANGELOG.md`::
  For Developer.
Release Note::
  For User. Using it to GitHub Release. This isn't managed by git.

== Prepare for release

:release_scripts_directory: scripts/release
:prepare_release_shell_path: {release_scripts_directory}/prepare-release.sh
link:{root_directory}/{prepare_release_shell_path}[
Run `bash {prepare_release_shell_path}` to prepare for release.^]

.`prepare-release.sh`
. Automatically bump versions
. Generate CHANGELOG as `CHANGELOG.md`
. Create a commit containing `CHANGELOG.md` +
  Commit message is `chore(release): prepare for <VERSION>`.
. Create git tag +
  Tag name is `<VERSION>`. +
  Open `GIT_EDITOR` to edit tag message.
  If you don't want edit tag message with `GIT_EDITOR`, add `GIT_EDITOR=true`.
  That's you run `GIT_EDITOR=true bash {prepare_release_shell_path}`.

:git_cliff_v081_url: {git_cliff_url}/blob/v0.8.1
:detailed_config_link: link:{git_cliff_v081_url}/examples/detailed.toml[Detailed^]
:scoped_config_link: link:{git_cliff_v081_url}/examples/scoped.toml[Scoped^]
[[changelog]]
== CHANGELOG.md

.Configuration File
link:{root_directory}/cliff.toml[cliff.toml^] +
`cliff.toml` is git-cliff default configuration file path.

[[example_repository]]
:example_repository_link: {github_url}/hituzi-no-sippo/git-commit-messages-example[example repository^]
.`git log --oneline` on {example_repository_link}
[%collapsible%open]
====
....
0924b6a (HEAD -> main, tag: v3.0.0) feat(cache)!: ticket #1 (close #1)
28b1463 feat: commit without scope
231f818 feat(key): security
5c4a906 revert(db): revert type commit
f0d0672 Revert "perf(db): perf type commit"
f79e6e6 perf(db): perf type commit
8aabc98 build(make): build type commit
2b647e5 ci(github-actions): ci commit type
2924ec9 style(editorconfig): style type commit
96385b3 test(jest): test type commit
ea29296 (tag: v2.0.0) feat(cache): use cache while fetching pages
2122322 feat(config): support multiple file formats
4080534 (tag: v1.0.1) chore(release): add release script
aabc853 refactor(parser): expose string functions
fb610c6 (tag: v1.0.0) docs(example)!: add tested usage example
c69284a fix(args): rename help argument due to conflict
2f23ca1 feat(parser): add ability to parse arrays
701abff docs(project): add README.md
09a05cf Initial commit.
....
====

.Reference Configuration
* {detailed_config_link}
* {scoped_config_link}

.`CHANGELOG.md` generated by the example repository
[%collapsible%open]
====
.`git-cliff`
[source, Markdown]
----
# Changelog

All notable changes to this project will be documented in this file.

## [3.0.0] - 2022-08-20

[v2.0.0](ea292960a0bd83a80040d55884c32d49c141af5e)...[v3.0.0](0924b6ade5e8fb62dac123f551b2223397c6c066)

### Breaking Change

#### Features

##### Cache

- Ticket #1 (close [#1](https://github.com/hituzi-no-sippo/git-commit-messages-example/issues/1)) (0924b6ade5e8fb62dac123f551b2223397c6c066)

### CI

#### Github Actions

- Ci commit type ([2b647e5d5779dd66764f066b9df52f39a9d80b80](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/2b647e5d5779dd66764f06
6b9df52f39a9d80b80))

### Features

### Performance

#### Db

- Perf type commit ([f79e6e69b5d890c2ce4001c62c9651f3c498a697](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/f79e6e69b5d890c2ce40
01c62c9651f3c498a697))

### Security

#### Key

- Security ([231f81871ea83b8797e661e17420b36fc5fa5cd4](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/231f81871ea83b8797e661e17420
b36fc5fa5cd4))

### Styling

#### Editorconfig

- Style type commit ([2924ec96fcee0e830349457414988364a49d8795](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/2924ec96fcee0e83034
9457414988364a49d8795))

### Testing

#### Jest

- Test type commit ([96385b3515c2fe51084f20a15ab787d07206fbc6](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/96385b3515c2fe51084f
20a15ab787d07206fbc6))

### Build

#### Make

- Build type commit ([8aabc9862b34402ffcba4a026c6921a4537d4b09](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/8aabc9862b34402ffcb
a4a026c6921a4537d4b09))

### Revert

#### Db

- Revert type commit ([5c4a906d60052ed043ee8f21af92e5a13d97e8fe](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/5c4a906d60052ed043
ee8f21af92e5a13d97e8fe))

## [2.0.0] - 2022-07-17

[v1.0.1](4080534f242669e0f48bc758256f2d577cf23793)...[v2.0.0](ea292960a0bd83a80040d55884c32d49c141af5e)

### Features

#### Cache

- Use cache while fetching pages ([ea292960a0bd83a80040d55884c32d49c141af5e](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/ea2929
60a0bd83a80040d55884c32d49c141af5e))

#### Config

- Support multiple file formats ([2122322a807752d8640e2b9ce30def57d6bc2bb5](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/2122322
a807752d8640e2b9ce30def57d6bc2bb5))

## [1.0.1] - 2022-07-17

[v1.0.0](fb610c6aa0d7e8b13278819eaa0bee10609ad572)...[v1.0.1](4080534f242669e0f48bc758256f2d577cf23793)

### Miscellaneous Tasks

#### Release

- Add release script ([4080534f242669e0f48bc758256f2d577cf23793](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/4080534f242669e0f4
8bc758256f2d577cf23793))

### Refactor

#### Parser

- Expose string functions ([aabc853c4940d9d8791a92cef36ccd786aeb2946](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/aabc853c4940d
9d8791a92cef36ccd786aeb2946))

## [1.0.0] - 2022-07-17

### Breaking Change

#### Documentation

##### Example

- Add tested usage example (fb610c6aa0d7e8b13278819eaa0bee10609ad572)

### Bug Fixes

#### Args

- Rename help argument due to conflict ([c69284a9c53055ae6bb42fcfe5c0e231ced72fbf](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/
c69284a9c53055ae6bb42fcfe5c0e231ced72fbf))

### Documentation

#### Project

- Add README.md ([701abffb06aafed1d4983451107a97a0c4ab17c2](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/701abffb06aafed1d498345
1107a97a0c4ab17c2))

### Features

#### Parser

- Add ability to parse arrays ([2f23ca1b8773c9250198499c260eba54a2e1644f](https://github.com/hituzi-no-sippo/git-commit-messages-example/commit/2f23ca1b8
773c9250198499c260eba54a2e1644f))

<!-- generated by git-cliff -->
----
====

=== Lint

:lint_generated_CHANGELOG_shell_path: scripts/release/lint-generated-CHANGELOG.sh
link:{root_directory}/{lint_generated_CHANGELOG_shell_path}[
Run `bash {lint_generated_CHANGELOG_shell_path}` to lint generated CHANGELOG
with git-cliff^].

.`lint-generated-CHANGELOG.sh`
. Using dprint to check markdown format
. Using markdownlint-cli to lint markdown

.Git hooks
pre-commit::
  Using  link:{pre_commit_config_file}#:~:text=id%3A%20lint%2Dgenerated%2DCHANGELOG%2Dwith%2Dmarkdown%2Dlinter[
  Lint generated CHANGELOG (local hook)^]


== Release note

The format of release notes is different from xref:changelog[CHANGELOG.md].
The format is based on link:https://keepachangelog.com/en/1.0.0/[
Keep a Changelog^].

.GitHub Actions
link:{workflows_directory}/create-github-release.yml[
Create GitHub Release on push tag^].

:release_note_config_path: .git-cliff/release-note.toml
.Configuration File
link:{root_directory}/{release_note_config_path}[{release_note_config_path}^]

:keep_a_changelog_config_link: link:{git_cliff_v081_url}/examples/keepachangelog.toml[Keep a Changelog^]
.Reference Configuration
* {detailed_config_link}
* {scoped_config_link}
* {keep_a_changelog_config_link}

The following commit types aren't written in the release notes :

* refactor
* style
* test
* ci
* build
* chore

:example_repository_xref: xref:example_repository[example repository]
.Release note generated by the {example_repository_xref}
[%collapsible%open]
====
.`git-cliff --config {release_note_config_path}`
[source, Markdown]
----
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [3.0.0] - 2022-08-20

### Breaking Change

#### Changed

##### Cache

- Ticket #1 (close [#1](https://github.com/hituzi-no-sippo/git-commit-messages-example/issues/1)) (0924b6ade5e8fb62dac123f551b2223397c6c066)

### Changed

#### Db

- Perf type commit (f79e6e69b5d890c2ce4001c62c9651f3c498a697)
- Revert type commit (5c4a906d60052ed043ee8f21af92e5a13d97e8fe)

#### Key

- Security (231f81871ea83b8797e661e17420b36fc5fa5cd4)

## [2.0.0] - 2022-07-17

### Added

#### Config

- Support multiple file formats (2122322a807752d8640e2b9ce30def57d6bc2bb5)

### Changed

#### Cache

- Use cache while fetching pages (ea292960a0bd83a80040d55884c32d49c141af5e)

## [1.0.0] - 2022-07-17

### Breaking Change

#### Documentation

##### Example

- Add tested usage example (fb610c6aa0d7e8b13278819eaa0bee10609ad572)

### Added

#### Parser

- Add ability to parse arrays (2f23ca1b8773c9250198499c260eba54a2e1644f)

### Documentation

#### Project

- Add README.md (701abffb06aafed1d4983451107a97a0c4ab17c2)

### Fixed

#### Args

- Rename help argument due to conflict (c69284a9c53055ae6bb42fcfe5c0e231ced72fbf)

<!-- generated by git-cliff -->
----
====

== Bump version

:cocogitto_url: https://docs.cocogitto.io
Bump version tool to using link:{cocogitto_url}[Cocogitto^].

.Configuration File
link:{root_directory}/cog.toml[cog.toml^]

=== Tag prefix

Tag prefix is `v`.
For examples `v0.1.0`, `v1.0.0`.

Set `tag_prefix = "v"` to configuration file for Cocogitto.
link:{cocogitto_url}/guide/#tag-prefix[
This is because Cocogitto has no prefix by default^],


'''

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2022 {author_link}
