= Shell
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.10.0
:revdate: 2022-08-18T21:02:22+09:00
:revremark: add git hook for shellcheck
:description: Shell
:copyright: Copyright (C) 2022 {author}
// Custom Attributes
:creation_date: 2022-07-24T16:00:52+09:00
:github_url: https://github.com
:root_directory: ../..
:pre_commit_config_file: {root_directory}/.pre-commit-config.yaml
:workflows_directory: {root_directory}/.github/workflows

:github_actions_marketplace_url: {github_url}/marketplace/actions
:sh_checker_link: link:{github_actions_marketplace_url}/sh-checker[sh-checker^]
== Formatter

:shfmt_link: link:{github_url}/mvdan/sh[shfmt^]
Using {shfmt_link}.

:pre_commit_for_shell_format_link: link:{github_url}/scop/pre-commit-shfmt[scop/pre-commit-hooks^]
.Git hooks
pre-commit::
  Using link:{pre_commit_config_file}#:~:text=%2D%20repo%3A%20https%3A%2F/github.com/scop/pre%2Dcommit%2Dhooks[
  pre-commit^] ({pre_commit_for_shell_format_link})

:filename: lint-shell.yml
:filename_on_pull_request: lint-shell-on-pull-request.yml
:run_shfmt_with_reviewdog_link: link:{github_actions_marketplace_url}/run-shfmt-with-reviewdog[run-shfmt-with-reviewdog^]
.GitHub Actions
* link:{workflows_directory}/{filename}[{filename}^] +
  Using {sh_checker_link}.
* link:{workflows_directory}/{filename_on_pull_request}[{filename_on_pull_request}^] +
  Using {run_shfmt_with_reviewdog_link}.

=== Q&A

[%collapsible]
====

[qanda]
Why divide workflows of GitHub Actions by events like push and pull request?::
On push event of GitHub Actions,
run-shfmt-with-reviewdog doesn't fail if there is a format violation.
It also won't fail if `fail_on_error = true`.
And run-shfmt-with-reviewdog can't reports result on push event. +
Want to job fail if there is a format violation on push,
so use sh-checker on push.
Use run-shfmt-with-reviewdog
because it's useful to report results by review comments.
As mentioned earlier,
run-shfmt-with-reviewdog doesn't reports result on push event.
Want to use run-shfmt-with-reviewdog on push and sh-checker on pull request,
so divide GitHub Actions workflows.

.Can't change `reporter` of run-shfmt-with-reviewdog
[NOTE]
======
`reporter` of run-shfmt-with-reviewdog can't be changed from `github-pr-review`.
That's run-shfmt-with-reviewdog can't set `github-check` to `reporter`.

.If there is a format violation at push, does the job fail?
[horizontal]
github-pr-review:: No
github-check:: Yes

See link:{github_url}/reviewdog/reviewdog#reporters[
reviewdog documentation^] for details.
======
====


== Linter

=== shellcheck

:shellcheck_link: link:https://www.shellcheck.net/[shellcheck^]
Using {shellcheck_link}.

:pre_commit_for_shellcheck_url: {github_url}/koalaman/shellcheck-precommit
:pre_commit_for_shellcheck_link: link:{pre_commit_for_shellcheck_url}[koalaman/shellcheck-precommit^]
.Git hooks
pre-commit::
  Using link:{pre_commit_config_file}#:~:text=repo%3A%20https%3A%2F/github.com/koalaman/shellcheck%2Dprecommit[
  pre-commit^] ({pre_commit_for_shellcheck_link}). +
  Request {pre_commit_for_shellcheck_url}/blob/master/.pre-commit-hooks.yaml#:~:text=language%3A%20docker_image[
  Docker^].

:filename: lint-shell.yml
:filename_on_pull_request: lint-shell-on-pull-request.yml
:run_shellcheck_with_reviewdog_link: link:{github_actions_marketplace_url}/run-shellcheck-with-reviewdog[run-shellcheck-with-reviewdog^]
.GitHub Actions
* link:{workflows_directory}/{filename}[{filename}^] +
  Using {sh_checker_link}.
* link:{workflows_directory}/{filename_on_pull_request}[{filename_on_pull_request}^] +
  Using {run_shellcheck_with_reviewdog_link}.

=== shellharden

Using shellharden to fix quotes (`+${hoo}+` => `"$hoo"`).

:filename: check-quoting-in-shell.yml
:cargo_install_link: link:{github_actions_marketplace_url}/cargo-install[cargo-install^]
.GitHub Actions
* link:{workflows_directory}/{filename}[{filename}^] +
  Using {github_actions_marketplace_url}.


'''

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2022 {author_link}
