---
name: Lint Markdown

on:
  push:
    paths:
      - "**.md"
      - ".dprint.json"

  pull_request:
    paths:
      - "**.md"
      - ".dprint.json"

jobs:
  format:
    name: Check format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check format with dprint
        # yamllint disable-line rule:line-length
        uses: hituzi-no-sippo/check@21681de30f5916de2235da7f22bf7462bb7004cb
        with:
          file-patterns: '"**/*.md"'
