---
name: Lint JSON

on:
  push:
    paths:
      - "**.json"
      - ".dprint.json"
  pull_request:
    paths:
      - "**.json"
      - ".dprint.json"

jobs:
  format:
    name: Check format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check format with dprint
        uses: hituzi-no-sippo/check@21681de30f5916de2235da7f22bf7462bb7004cb
        with:
          file-patterns: '"**/*.json"'

  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download validater
        id: get_validater
        # yamllint disable rule:line-length
        run: |
          curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel \
            && chmod +x dasel
          echo "executable=$(pwd)/dasel" >> "$GITHUB_OUTPUT"
        # yamllint enable rule:line-length

      - name: Validate with dasel
        run: |
          ${{ steps.get_validater.outputs.executable }} validate "**.json"
