---
name: Lint INI

on:
  push:
    paths:
      - "**.ini"
  pull_request:
    paths:
      - "**.ini"

jobs:
  format:
    name: Check format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check format with editorconfig
        uses: docker://mstruebing/editorconfig-checker
