---
name: Lint Git Commit Message

on: [push, pull_request]

jobs:
  conventional-commits:
    name: Check Conventional Commit Compliance with Cocogitto
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Get the full git history.
          # https://docs.cocogitto.io/ci_cd/#conventional-commits-check
          fetch-depth: 0

      - name: Conventional Commit Check with Cocogitto
        uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true

  format:
    name: Check format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Markdown formatter and linter
        uses: ./.github/actions/setup-markdown-formatter-and-linter

      - name: Output git commit message to file
        uses: ./.github/actions/output-git-commit-message-to-file
        with:
          file: log.md

      - name: Add file to git index
        run: git add log.md

      - name: Format commit message
        run: bash scripts/git/format-commit-msg.sh log.md

      - name: Check for formatting changes
        run: git diff --exit-code log.md
